backend:
  name: github
  repo: rugia813/gatsby-portfolio-2021
  branch: master
media_folder: static/assets
public_folder: /assets
collections:
  - label: Work
    name: work
    folder: markdown/work
    create: true
    fields:
      - { name: slug, label: Slug }
      - { name: date, label: Date, widget: date, format: 'DD/MM/YYYY' }
      - { name: title, label: Title }
      - { name: cover, label: Cover, widget: image }
      - { name: tags, label: Tags, widget: list }
      - { name: body, label: Body, widget: markdown }
  - label: "About"
    name: "about"
    files:
    - label: "Intro"
      name: "intro"
      file: "markdown/about/intro.json"
      fields:
        - {label: Content, name: content, widget: markdown}
    - label: Skills
      name: skills
      file: "markdown/about/skills.json"
      fields:
        - label: Skill
          name: skill
          widget: list
          fields:
          - {label: Name, name: name, widget: string}
          - {label: Level, name: level, widget: string}
          - {label: Logo, name: logo, widget: image, required: false}